ministryofjustice/hmpps-non-associations-api

.circleci/config.yml
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/dto/prisonapi/NonAssociationDetails.kt

The assigned living unit fields could be null and in general a non-association could be with someone who left prison (but may return, and that's why it's imporant to still retain the non-association)
I've also update the Swagger documentation for the fields accordingly.
**NOTE**: While I was getting an exception when Spring Boot/Jackson for the missing mandatory `String` field, it didn't complain about the missing `Long` field and implicitly converted it to `0`.
We should distinguish between `0`s and `null`s are these are different concept, one signifify the absence of information (e.g. there is no assigned unit) while the other imply knowledge (e.g. the assigned unit is XYZ). We don't want `0` to be possibly interpreted as an ID for a real living unit as that would be wrong.
That's why …

NON-10: Optional assigned living unit fields

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/config/HmppsNonAssociationsApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/dto/NonAssociationDetails.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/dto/prisonapi/LegacyNonAssociationDetails.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/jpa/ReasonType.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/PrisonApiResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/NonAssociationsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/PrisonApiService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/integration/wiremock/PrisonApiMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/jpa/repository/ReasonTypeRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/PrisonApiResourceTest.kt

- `GET /prisoner/{prisonerNumber}/non-associations`
- this is just a placeholder/starting point and very much subject to change (and this is made explicit in the Swagger docs)
- endpoint uses `ROLE_NON_ASSOCIATIONS` as discussed although authorisation may need further discussion
- the response format is just a stub at this stage (as design is still in flux and this may affect data model) - but the main point is that this format/dto class is different and separate from the one used by the legacy/Prison API endpoint
- This is mainly to allow us design freedom, however those two formats will have to have some level of compatibility for synchronisation purposes obviously
- handling of `AccessDenied` exceptions so that the client gets an appropriate `403 Forbidden` rather than a `500 Internal …

NON-10: Skeleton of new non-associations endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/config/HmppsNonAssociationsApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/dto/NonAssociation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/jpa/NonAssociation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/jpa/repository/NonAssociationsRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/NonAssociationsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/jpa/repository/NonAssociationsRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/NonAssociationsServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/util/TestData.kt

- ability to create a non-association (open). required `ROLE_NON_ASSOCIATIONS` role with `write` scope
- better handling of some validation exceptions
- non-association `comment` is mandatory in JPA entity (was already non-nullable in DB)

NON-86: `POST /non-associations` endpoint

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/config/HmppsNonAssociationsApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/NonAssociationsService.kt
src/main/resources/db/migration/V1_8__non_association__increase_authorised_by_length.sql
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt

Added `GET /non-associations/{id}` endpoint to retrieve a single non-association

NON-87: Get single non association by ID

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/dto/NonAssociation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/dto/PrisonerNonAssociations.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/NonAssociationsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/util/TestData.kt

Improvements to `GET /prisoner/:prisonerNumber/non-associations`:
- `includeClosed` query param to also get closed non-association, default `false`, only open non-associations are returned
- `includeOtherPrisons` query param to also get non-associations with prisoners in other prisons, default `false`, by default only non-associations with prisoners in same prison [as given prisoner] are returned
- expose non-associations' `id`s
- fixes to `PrisonerNonAssociations` DTO related to closed non-associations
-  correctly expose values related to closed non-associations
- `closedAt` type is a `LocalDateTime`, not a string
- corrected swagger documentation for `NonAssociation`'s `id` which is always present
- added a couple more test prisoners in the OffenderSearch API test data, useful for …

NON-88: Filtering for endpoint to get a prisoner non-associations

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/config/HmppsNonAssociationsApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/dto/PrisonerNonAssociations.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/NonAssociationsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt

- non-associations returned in order of creation by default (from newer to older)
- optional `sortBy`/`sortDirection` query params to control sorting criteria and direction
- can be sorted by creation time (default), last name or first name of the other prisoner involved in the non-association
- should be trivial to add more sorting options if/when necessary

NON-88: Ability to sort a prisoner non-associations

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/jpa/repository/NonAssociationsRepository.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/NonAssociationsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/jpa/repository/NonAssociationsRepositoryTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt

Similar to the `POST /non-associations/between` endpoint but returns non-associations as long as any of the involved prisoners was part of the request list.
Like the "between" endpoint returns only open non-associations by default but it's possible to request for only closed or all non-associations.

NON-207: Endpoint to return non-associations involving a list of prisoners

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResource.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt

… so that clients do not need to hard-code expected inputs

Expose enumerated field types publicly at `/constants`

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/NonAssociationsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt

- optional `prisonId` query param
- when provided information about the prisoners are retrieved and only non-associations between prisoners which are both at the given prison are returned
- response format is unchanged

NON-215: Ability to filter non-associations by prison for "between"/"involving" endpoints

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/NonAssociationsService.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/OffenderSearchService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/integration/wiremock/OffenderSearchMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt

Mainly that plus a couple of other tweaks:
- use `flatMap()` instead of `map()` + `flatten()`
- added a note in `getPrisonerNonAssociations()` on why in that method we use `flatMapTo()` instead of `flatMap()` to be sure the "key" prisoner's prisoner number is always in the request to Offender Search API (a test covers that)

NON-215: Don't send duplicated prisoner numbers to Offender Search API

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/dto/ListOptions.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResource.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/NonAssociationsServiceTest.kt

Even though the staff-facing site will have to sort non-association lists internally, we might as well have the same options in the api to prevent confusion.

NON-193: Allow sorting non-associations by more options

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResource.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt

- endpoints that read non-associations require `ROLE_READ_NON_ASSOCIATIONS` role (instead of `ROLE_NON_ASSOCIATIONS` role)
- endpoints to create/update/etc non-associations require `ROLE_WRITE_NON_ASSOCIATIONS` role and `write` scope (instead of `ROLE_NON_ASSOCIATIONS` role + `write` scope)
- endpoint to delete non-associations require `ROLE_DELETE_NON_ASSOCIATIONS` role and `write` scope (this was already the case but it's consistent now)
**NOTE**: Sync/migrations endpoints are unchanged

NON-177: More granular permissions

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/config/HmppsNonAssociationsApiExceptionHandler.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/SyncAndMigrateResourceTest.kt

Delete only occurs where the prisoner numbers are the same.

NON-233 When duplicate detected - raise 409 response instead of 400 

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/settings.gradle.kts
buildSrc/src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/CloudPlatformTask.kt
buildSrc/src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/Environment.kt
buildSrc/src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/PortForwardRDSTask.kt
buildSrc/src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/PortForwardRedisTask.kt
buildSrc/src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/PortForwardTask.kt
buildSrc/src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/RevealSecretsTask.kt

There are 3 common tasks that could be more usefully automated:
• connecting a local port to an AWS RDS instance in Cloud Platform
• connecting a local port to an AWS ElastiCache Redis instance in Cloud Platform
• listing and revealing kubernetes secrets in Cloud Platform
…each of which could be performed with a sequence of shell commands, but they would be more complex, project-specific and the first two require clean-up steps.
For example, [connecting to RDS](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/rds-external-access.html):
```shell
kubectl \
--namespace hmpps-non-associations-dev \
get secret dps-rds-instance-output \
-o jsonpath={.data.rds_instance_address} \
| base64 -D \
| read rds_instance_address
kubectl \
--namespace …
```

Gradle tasks to connect a local port to RDS or Redis in Cloud Platform and to reveal kubernetes secrets

---

helm_deploy/values-prod.yaml

This is enabling the preprod syncing of the generic service helm chart, [see docs](https://github.com/ministryofjustice/hmpps-helm-charts/tree/main/charts/generic-service#prison-postgres-database-restore-cronjob
).
This is using the proprod DB secrets (in the production namespace) created in [this PR Cloud Platform environments PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/16797).
Similar to what already done for Incentives ([see Incentives PR](https://github.com/ministryofjustice/hmpps-incentives-api/pull/345/files#diff-bb4e80ba0a6c43663498b44c19e42c074dcceac3d9564b49801202073b5c87ffR14)).

NON-263: Enable preprod database sync from prod DB

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/LegacyResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResource.kt

- removed WIP note in new endpoint
- added a note in legacy endpoint doc to encourage use of new endpoints
**NOTE**: Do NOT merge this until we're done with migration/syncing and we consider the new API "online".

NON-265: Swagger docs: Encourage use of new API endpoints

---

helm_deploy/values-prod.yaml

Switched feature flag in production so that `/legacy` endpoint is now using DB instead of proxying to Prison API (which uses NOMIS data)
This is used in [this `when` statement](https://github.com/ministryofjustice/hmpps-non-associations-api/blob/671d2a9df9a2b97234161474752dec2dbd83da42/src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/NonAssociationsService.kt#L244-L253):
```Kotlin
return when (featureFlagsConfig.legacyEndpointNomisSourceOfTruth) {
true -> prisonApiService.getNonAssociationDetails(prisonerNumber, currentPrisonOnly, excludeInactive)
false -> {
val inclusion = if (excludeInactive) NonAssociationListInclusion.OPEN_ONLY else NonAssociationListInclusion.ALL
return getPrisonerNonAssociations(
prisonerNumber,
NonAssociationListOptions(inclusion = …
```

NON-262: Legacy endpoint using DB in production

---

clients/node/README.md
clients/node/src/errorTypes.ts
clients/node/src/responseTypes.ts
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/config/HmppsNonAssociationsApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/dto/LegacyPrisonerNonAssociations.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/dto/PrisonerNonAssociations.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/dto/offendersearch/OffenderSearchPrisoner.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/NonAssociationsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/NonAssociationsServiceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/util/TestData.kt

The api now responds with 409 CONFLICT when trying to create a non-association with a prisoner with a null location.
Also, allow for offender search results that have no prison name or ID. Because those fields _can_ be null, we are forced to propagate the nullability into _this_ api.
**It does mean that our api contract changes!**
Related: [ui#184](https://github.com/ministryofjustice/hmpps-non-associations/pull/184) & [ui#185](https://github.com/ministryofjustice/hmpps-non-associations/pull/185)

NON-287: Disallow adding a non-associations to prisoners with null locations

---

buildSrc/src/main/kotlin/uk/gov/justice/digital/hmpps/gradle/PortForwardTask.kt

Default to port `12345` instead of the corresponding standard ports. Especially in the case of RDS, accidentally leave the port forward to a `preprod`/`prod` DB while running tests could be dangerous.

Use non-standard port to connect to RDS/Redis

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml

Enable 'scheduled downtime' feature of generic-service helm chart: https://github.com/ministryofjustice/hmpps-helm-charts/tree/main/charts/generic-service#scheduled-downtime
> To enable this feature, you first need to add a `scheduled-downtime-serviceaccount`
> Service Account to your namespace, with permissions to scale your deployment.
The required kubernetes `ServiceAccount` is already there:
- `dev`: https://github.com/ministryofjustice/cloud-platform-environments/blob/ed74f5b567c5e8e2f2aab90a92263f23021ca106/namespaces/live.cloud-platform.service.justice.gov.uk/hmpps-non-associations-dev/resources/scheduled-downtime.tf
- `preprod`: https://github.com/ministryofjustice/cloud-platform-environments/blob/ed74f5b567c5e8e2f2aab90a92263f23021ca106/namespaces/live.cloud-platform.service.justi …

NON-303: Stop non-prod instances during non-working hours

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/dto/NonAssociation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/dto/PrisonerNonAssociations.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/jpa/NonAssociation.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/NonAssociationsService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/NonAssociationsServiceTest.kt

This is not yet exposed when retrieving individual non-association records, but was already available when listing non-associations for a given prisoner.
The api contract doesn't change, but our record-keeping is improved.

NON-299: Record user creating a non-association using this api

---

.circleci/config.yml
helm_deploy/hmpps-non-associations-api/values.yaml

… keeping `dev` unrestricted.
Don’t merge until [ui#201](https://github.com/ministryofjustice/hmpps-non-associations/pull/201) is tested.

Move `prod` and `preprod` to use the same shared IP address allow lists

---

helm_deploy/hmpps-non-associations-api/values.yaml

Ref: [hmpps-ip-allowlists#2](https://github.com/ministryofjustice/hmpps-ip-allowlists/pull/2)

Remove health-kick from allow list since it is now within Cloud Platform

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/config/HmppsNonAssociationsApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/LegacyResource.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResource.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/SyncResourceTest.kt

• Throw `NonAssociationNotFoundException ` instead of _occasionally_ a 404 Not Found `ResponseStatusException` – slightly changes the error response text
• Return 415 Unsupported Media Type instead of 400 Bad Request when the request’s content type is incorrect
• Fix tests for invalid body checking that used incorrect roles or tuples instead of maps
• Throw `ValidationException` instead of 400 Bad Request `ResponseStatusException` so the meaning is more consistent – slightly changes error response `userMessage` text
While some error response text changes slightly, this shouldn't matter to clients as they wouldn't display it to users directly. Similarly, 415 instead of 400 is the more appropriate status for incorrect content types and nobody would have relied on this.

Improve exception handling

---

.github/workflows/publish-node-client.yml
LICENSE
clients/node/.gitignore
clients/node/README.md

Version 0.4.0 was already manually published to [npmjs.com](https://www.npmjs.com/package/@ministryofjustice/hmpps-non-associations-api)

Publish node REST client to npmjs.com

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/config/OpenApiConfiguration.kt

`securitySchemes` in OpenAPI output had a few issues…
1) `in` and `name` only apply to “apiKey” type (not the “http” that we use)
2) `openIdConnectUrl` only applies to “openIdConnect” type (not the “oauth2” that we use)
See https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.1.md#fixed-fields-23
[Copied from incentives-api](https://github.com/ministryofjustice/hmpps-incentives-api/pull/549/commits/9f943c4cadbb81a3d176c67a6157d511bfd555b1)

NON-318: Copy OpenAPI fixes from incentives

---

build.gradle.kts
src/main/resources/definitions.json

This is now possible because DPR library has fixed problem causing exceptions when the date was null:
https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/issues/122

NON-347: Format `close_date` like other dates

---

build.gradle.kts
src/main/resources/definitions.json

DPR support for filtering was added in version `3.7.2`: https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/blob/main/CHANGELOG.md#372

NON-347: Use boolean type for `is_closed` field

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/config/HmppsNonAssociationsApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/SubjectAccessRequestService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt

The endpoint now responds `204 No Content` when no non-associations for the given prisoner were found or when none of them were within the given date range.
**NOTE**: Offender Search API could _potentially_ not have information on some of the prisoners involved in the non-associations found. This is an edge case but without these information (names, etc...) we cannot construct the response correctly so the endpoint will continue to respond `404 Not Found` in these cases.
In my opinion this is better than responding `204 No Content` and misleading the client into believing there were no information on the given subject. It shouldn't happen in theory anyway.

NON-358: SAR endpoint responds `204 No Content` when no information matching

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/config/HmppsNonAssociationsApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/OffenderSearchService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt

Instead of throwing a generic `NotFound` exception. This potentially allows the handling of this case differently if required.
It should fix https://github.com/ministryofjustice/hmpps-non-associations-api/issues/258

NON-358: OS service throws a specific exception when some prisoners are missing

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/config/HmppsNonAssociationsApiExceptionHandler.kt
src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/SubjectAccessRequestService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt

The Subject Access Request (SAR) endpoint was responding `404 Not Found` when a prisoner number was not found in Offender Search API.
However the SAR endpoint contract doesn't expect 404s: https://non-associations-api-dev.hmpps.service.justice.gov.uk/swagger-ui/index.html#/Subject%20Access%20Request/getSarContentByReference
This case is still different than the case where we didn't find non-associations for the subject.
The endpoint now responds `209` "Subject Identifier is not recognised by this service" in this case.

NON-358: SAR: Respond 209 when a prisoner is not found (in OS API)

---

.circleci/config.yml

Ref [hmpps-template-kotlin#209](https://github.com/ministryofjustice/hmpps-template-kotlin/pull/209)

NON-318: Use same version of java for Veracode scanning as required by HMPPS plugins

---

Dockerfile

…since gradle now complains about not finding the right toolchain

NON-318: Build application using JDK (not JRE) base image

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

Send alerts to our Slack dev channel (`#non-associations-dev`) instead of sending them to `#dps_alers`/`#dps_alerts_non_prod`.

NON-318: Send alerts to dev channel

---

src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/service/OffenderSearchService.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/integration/wiremock/OffenderSearchMockServer.kt
src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsnonassociationsapi/resource/NonAssociationsResourceTest.kt

This should fix the problem of propagating an error from offender search into responses from this api that should have returned empty lists of non-associations

NON-369: Prevent calling search when no non-associations are found
